CREATE TABLE gift_requests
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    recipient_name    VARCHAR(255),
    age               INTEGER,
    hobbies           VARCHAR(255),
    budget            VARCHAR(255),
    full_request_text VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_gift_requests PRIMARY KEY (id)
);